### ISSUE TITLE
ERROR: 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by arncode90** [T-Dynamos/materialyoucolor-pyhton#7]
I am getting this error. How to solve this?
```
02-04 15:19:24.047 28067 28291 I python  :  Traceback (most recent call last):
02-04 15:19:24.047 28067 28291 I python  :    File "/content/.buildozer/android/app/main.py", line 2, in <module>
02-04 15:19:24.048 28067 28291 I python  :    File "/content/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/succoclaim/armeabi-v7a/kivymd/app.py", line 67, in <module>
02-04 15:19:24.048 28067 28291 I python  :    File "/content/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/succoclaim/armeabi-v7a/kivymd/theming.py", line 58, in <module>
02-04 15:19:24.048 28067 28291 I python  :    File "/content/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/succoclaim/armeabi-v7a/materialyoucolor/quantize/__init__.py", line 1, in <module>
02-04 15:19:24.048 28067 28291 I python  :  ImportError: dlopen failed: "/data/data/com.succo.succoclaim/files/app/_python_bundle/site-packages/materialyoucolor/quantize/celebi.so" is 64-bit instead of 32-bit
02-04 15:19:24.048 28067 28291 I python  : Python for android ended.
```

Buildozer.spec
```
requirements = python3, kivy, https://github.com/kivymd/KivyMD/archive/master.zip, materialyoucolor, exceptiongroup, asyncgui, asynckivy, pillow
android.archs = armeabi-v7a
```

[Kivy        ] v2.3.0
[Python    ] v3.11.5 (main, Feb  4 2024, 09:44:36) 
[KivyMD   ] 2.0.1.dev0, git-Unknown, 2024-02-04

**Comment by arncode90** [comment]
I follow [FilipeMarch](https://github.com/FilipeMarch) post and its working. Running perfectly on mobile.
https://github.com/T-Dynamos/materialyoucolor-python/issues/5#issuecomment-1916063417
